modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT License"
issueTrackerURL = ""
[[mods]]
modId = "sleep"
version = "${file.jarVersion}"
displayName = "Sleep"
authors = "TwinSouls"
credits = ""
description = '''
A sleep overhaul mod looking to make sleep a more engaging an integral part of the survival experience.
'''
[modproperties.sleep]
catalogueImageIcon = "icon.png"
[[dependencies.Sleep]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.Sleep]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.3)"
ordering = "NONE"
side = "BOTH"
